name: CI

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
      - run: npm ci
      - run: npm run lint --if-present
      - run: npm test -- --ci --runInBand
      - run: npm run build --if-present
      - uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
